"""Render docs/rules.md from the rule metadata: python -m spl_lint.docs > docs/rules.md"""

from __future__ import annotations

from .rules import all_rules

_CATEGORIES = [
    ("syntax", "Syntax"),
    ("correctness", "Correctness: runs, but returns the wrong results"),
    ("performance", "Performance: slow, expensive, or silently truncated"),
    ("style", "Style"),
]


def render_markdown() -> str:
    rules = all_rules()
    lines = [
        "# spl-lint rules",
        "",
        "<!-- Generated by `python -m spl_lint.docs`; do not edit by hand. -->",
        "",
        "| ID | Name | Default severity | Summary |",
        "|----|------|------------------|---------|",
    ]
    for r in rules:
        lines.append(f"| [{r.id}](#{r.id.lower()}-{r.name}) | `{r.name}` | {r.severity} | {r.summary} |")
    for category, title in _CATEGORIES:
        lines += ["", f"## {title}"]
        for r in (r for r in rules if r.category == category):
            lines += [
                "",
                f"### {r.id} {r.name}",
                "",
                f"**Default severity:** {r.severity}",
                "",
                r.doc(),
                "",
                "Bad:",
                "",
                "```spl",
                r.bad,
                "```",
                "",
                "Good:",
                "",
                "```spl",
                r.good,
                "```",
            ]
    return "\n".join(lines) + "\n"


if __name__ == "__main__":
    import sys

    sys.stdout.write(render_markdown())
