[Brute force against admin accounts]
cron_schedule = */15 * * * *
search = index=auth action=failure (user=admin OR user=root) \
| bin _time span=10m \
| stats count as eventcount by src _time \
| where eventcount > 20
